# Generated by Django 4.1.12 on 2023-11-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_articlestep_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='description2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='file1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='step',
            name='file2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
