# Generated by Django 4.1.12 on 2023-11-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_step_description1_alter_step_description2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='step_number',
            new_name='ordinal_number',
        ),
        migrations.AlterField(
            model_name='step',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='step',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
