# Generated by Django 4.2.7 on 2024-01-22 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
        ('editor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.article'),
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
