# Generated by Django 4.1.12 on 2023-11-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0003_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.TextField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
