# Generated by Django 4.1.12 on 2023-11-06 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor_app', '0004_report_status_alter_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
