# Generated by Django 4.1.12 on 2023-11-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0005_alter_report_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
