# Generated by Django 4.1.12 on 2023-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0007_alter_report_additional_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
