# Generated by Django 4.1.12 on 2023-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0008_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='changes_applied',
            field=models.BooleanField(default=False),
        ),
    ]
