# Generated by Django 4.1.12 on 2023-11-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0009_report_changes_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='changes_applied',
        ),
    ]
