# Generated by Django 4.1.12 on 2023-11-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0010_remove_report_changes_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
