# Generated by Django 4.2.7 on 2023-12-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0011_alter_report_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='additional_file',
            field=models.FileField(upload_to=''),
        ),
    ]
