# Generated by Django 4.2.7 on 2024-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0015_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
    ]
