# Generated by Django 4.2.7 on 2024-01-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0016_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='additional_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
